pypy/pypy

- .github/workflows/named-branches.yml
Via https://github.com/Julian/named-branch-action/issues/2#issuecomment-1873453432
> Update the named-branches workflow to a (hopefully) working version.

- extra_tests/cffi_tests/test_version.py
- pypy/module/_cffi_backend/test/test_file.py
PR #4814 change the directory name, this is a follow up to fix the failing tests.
> Fixes to tests after change in cffi metadata directory name

- pypy/doc/faq.rst
> DOC: update FAQ for move to github

- .github/workflows/translate.yml
- pypy/conftest.py
- pypy/objspace/std/test/test_methodcache.py
add a flaky marker and use it to skip test that sometimes fails
> skip flaky test on CI

- pypy/module/_rawffi/test/test__rawffi.py
- pypy/module/array/test/test_array.py
- rpython/rtyper/lltypesystem/ll2ctypes.py
- rpython/rtyper/lltypesystem/test/test_rffi.py
>  revert 6906755 and skip untranslated tests 

- extra_tests/test_scandir.py
- pypy/module/posix/test/test_scandir.py
- rpython/annotator/test/test_annrpython.py
- rpython/annotator/test/test_annrpython_py2.py
- rpython/flowspace/flowcontext.py
- rpython/flowspace/specialcase.py
- rpython/flowspace/test/test_objspace.py
- rpython/flowspace/test/test_objspace_py2.py
- rpython/flowspace/test/test_print_function.py
- rpython/memory/test/test_transformed_gc.py
- rpython/translator/c/test/test_standalone.py
- rpython/translator/c/test/test_standalone_print_function.py
- rpython/translator/goal/targetprintfunction.py
xref #4860 
@cpburnz is 508538bef the test you were thinking about?
> add a test of scan_dir with symlink and unicode

- pypy/tool/release/package.py
> remove top level __init__.py (issue 4885)

- pypy/module/exceptions/interp_exceptions.py
- pypy/module/exceptions/test/apptest_exceptions.py
see https://docs.python.org/3/whatsnew/3.11.html#whatsnew311-pep678
@cfbolz
> Implemented BaseException.add_note (PEP678)

- pypy/module/cpyext/test/test_typeobject.py
- pypy/module/cpyext/typeobject.py
- pypy/module/cpyext/unicodeobject.py
> Fix cpyext incompatabilities in getset, Py_UNICODE

- pypy/module/cpyext/modsupport.py
- pypy/module/cpyext/stubs.py
- pypy/module/cpyext/test/test_module.py
> add PyModule_GetFilenameObject and PyModule_GetNameObject

- rpython/conftest.py
- rpython/memory/gc/incminimark.py
- rpython/memory/gc/test/test_direct.py
should address #4925 and #3959
> Gc arraycopy incrementality bug

- rpython/memory/gc/incminimark.py
- rpython/memory/gc/test/test_direct.py
a bunch of new random test cases to the GC revealed more GC bugs, this time about pinning objects that already have a shadow.
> fix pinning/shadow interaction bugs

- .github/workflows/rpython-unit-tests.yml
- pypy/module/faulthandler/faulthandler.c
- rpython/rlib/rvmprof/cintf.py
- rpython/rlib/rvmprof/src/rvmprof.h
- rpython/rlib/rvmprof/src/shared/_vmprof.c
- rpython/rlib/rvmprof/src/shared/vmp_stack.c
- rpython/rlib/rvmprof/src/shared/vmp_stack.h
- rpython/rlib/rvmprof/src/shared/vmprof.h
- rpython/rlib/rvmprof/src/shared/vmprof_common.c
- rpython/rlib/rvmprof/src/shared/vmprof_common.h
- rpython/rlib/rvmprof/src/shared/vmprof_config.h
- rpython/rlib/rvmprof/src/shared/vmprof_unix.c
- rpython/rlib/rvmprof/src/shared/vmprof_win.c
- rpython/rlib/rvmprof/traceback.py
Toward #5057: update to latest vmprof HEAD
> update to vmprof-0.4.17

- pypy/interpreter/app_main.py
> always initialize locale by calling setlocale(LC_CTYPE, '')

- lib-python/3/threading.py
This is a very simple PR that fixes [the race](https://github.com/pypy/pypy/issues/5079) by removing one problematic `assert` statement and suppressing `RuntimeError` raised due to multiple `lock.release()` calls. If it seems strange to some, well, it is. I too wanted a more sophisticated solution.
More in-depth details are in the [my patch description](https://github.com/x42005e1f/aiologic/blob/760ab3dbe9cb59d1f3bb3dcd90b5a85b1f6f639c/src/aiologic/lowlevel/patcher.py#L403). There are also tests you can use to check the solution. And unlike my patch, it doesn't make additional optimizations as they are not relevant to the solution.
Side effect: direct `Thread._stop()` calls will succeed. But it is quite difficult to distinguish such from a typical race condition, so the lesser evil is …
> Fix race in Thread.join()

- lib-python/3/test/test_concurrent_futures.py
This PR fixes hangs in tests due to PyPy garbage collector behavior. Related to #4994.
> Fix test_concurrent_futures.py hangs

- .github/PULL_REQUEST_TEMPLATE.md
Second typo.
( It's always nice when people have to add a warning because of you :) )
> Second typo in PULL_REQUEST_TEMPLATE.md

- pypy/module/cpyext/parse/cpyext_object.h
Alternative approach to sendfunc. Hopefully supersedes #5170.
I do plan to write a test for this fairly soon, but proposing this PR now just to see if it works at all. So treat it as draft until the test.
> Fix sendfunc definition second go

- .github/workflows/pre-commit.yml
- .github/workflows/rpython-unit-tests.yml
- .github/workflows/translate.yml
- update ubuntu test image to 24.04, 20.04 is deprecated
- drop py3.10, py3.9
> refresh CI

- pypy/module/cpyext/test/gh5207.c
- pypy/module/cpyext/test/test_userslots.py
- pypy/objspace/descroperation.py
- pypy/objspace/test/apptest_descroperation.py
Fix 3-argument `__pow__` to try `__rpow__` as well
> Py3.10 rpow cpyext

- pypy/module/_hpy_universal/interp_type.py
Related to https://github.com/pypy/pypy/issues/5277
I just followed @cfbolz's advice.
Impressive that such tiny changes (https://github.com/pypy/pypy/pull/5294/commits/acf0f0f8ec103929c12ea38e58dd57549a4faa78) give such result...
Before:
```
cpy                    hpy
----------------    -------------------
TestHeapType::test_allocate_and_collect       1427.26 us      4747.94 us [3.33]                 
TestHeapType::test_allocate_obj                958.88 us      4003.63 us [4.18]                 
TestHeapType::test_allocate_obj_and_die       1342.95 us      1950.01 us [1.45]                 
TestHeapType::test_method_lookup                10.90 us        47.33 us [4.34]                 
TestHeapType::test_noargs                      242.10 us       178.68 us [0.74] …
```
> Hpy interp type

- rpython/rlib/parsing/test/test_translate.py
- rpython/rlib/parsing/test/test_translate_lexer.py
This is a warmup for me trying to improve the parsing library in rlib
> Replace a test class that has only a single test method with function
