pypy/pypy

.github/workflows/named-branches.yml

And limit how much we fetch so we don't wait ages.

Give the named branches token write access to push.

---

pypy/module/cpyext/parse/cpyext_object.h

@mgorny, this is enough to fix #4186, right?

change PyBUF_MAX_NDIM back to 36 for ABI consistancy (issue #4816)

---

extra_tests/test_startup.py
pypy/module/sys/initpath.py
pypy/module/sys/test/apptest_initpath.py

Fixes #4003.
Based on https://github.com/python/cpython/blob/v2.7.18/PC/getpathp.c#L414-L415, `sys.executable` should always be initialized from `GetModuleFileName` on win32 if possible.

Init sys.executable from GetModuleFileName on win32

---

pypy/doc/build.rst
pypy/doc/coding-guide.rst
pypy/doc/contributing.rst
pypy/doc/cpython_differences.rst
pypy/doc/dev_method.rst
pypy/doc/faq.rst
pypy/doc/index.rst
pypy/doc/install.rst
pypy/doc/project-ideas.rst
pypy/doc/sandbox.rst

This PR aims to help the migration effort to GitHub by replacing mentions of Heptapod and Mercurial with GitHub and git.
So far, it's missing some hg command translations.

Replace Heptapod and Mercurial mentions with GitHub and git

---

lib-python/3/test/support/__init__.py

It seems that the import was supposed to be removed as part of:
commit aeb68b0468010b31c3d8bb2e529b20f8c0e2a10a
Author:     Matti Picus <matti.picus@gmail.com>
AuthorDate: 2023-08-16 22:17:12 +0200
Commit:     Matti Picus <matti.picus@gmail.com>
CommitDate: 2023-08-16 22:17:12 +0200
create test c-extension modules as part of the build, not as part of testing
However, it seems that a second copy persisted after the merge to py3.10 branch.  Remove it as well.

remove the other _testmultiphase_build import from test.support

---

pypy/module/cpyext/include/methodobject.h

This should fix `METH_FASTCALL` so it is included in the 3.10 limited API like in CPython.
Fixes #4050

fix limited API guard for METH_FASTCALL to match CPython

---

pypy/module/cpyext/include/object.h
pypy/module/cpyext/object.py
pypy/module/cpyext/test/test_object.py

Fixes #4044 by calling `space.is_w` for `Py_Is`

implement Py_Is in terms of space.is_w (issue #4044)

---

pypy/tool/release/repackage.sh

Explicitly configure git-archive to support .tar.bz2 format when running the release script.  There is no harm to redefine it, so just do it unconditionally.

fix release script to define bz2 command

---

pypy/module/posix/interp_scandir.py
pypy/module/posix/test/test_scandir.py

fixes #4860. As stated in the issue, someday we should refactor all uses of `FileEncoder` to never call `as_unicode`

fix os.scandir for unicode filenames on windows

---

rpython/annotator/test/test_annrpython.py
rpython/annotator/test/test_annrpython_py2.py
rpython/flowspace/flowcontext.py
rpython/flowspace/specialcase.py
rpython/flowspace/test/test_objspace.py
rpython/flowspace/test/test_objspace_py2.py
rpython/flowspace/test/test_print_function.py
rpython/translator/c/test/test_standalone.py
rpython/translator/c/test/test_standalone_print_function.py
rpython/translator/goal/targetprintfunction.py

Recreates https://github.com/pypy/pypy/pull/4835 (after I deleted + recreated my fork)
This is mostly selfish because my code editor no longer supports the python2 print syntax. It makes both of the following valid rpython snippets (so long as they live in separate files):
```python
from __future__ import print_function
print("oh no!", end="")
```
```python
print "foo",
```
Have to admit I also have my eye on making "six-compatible" python valid rpython - for future editor, linter support etc.

RPython: add support for from __future__ import print_function

---

rpython/memory/test/test_transformed_gc.py

this is based on a hunch that the flake in these tests is due to deferred gc of spurious entries in the header2obj WeakKeyDictionary (which would be why cpython runs of the tests are more stable) ... to test the theory I need to trigger a lot of CI runs
closes #4866

make test_transformed_gc tests more stable

---

pypy/module/imp/interp_imp.py

Fixes #4878
The fixes for #3833 did not actually fix the issue: the first commits did not translate, and the subsequent fixes broke `importlib.machinery.EXTENSION_SUFFIXES`. This is a better fix.

Correct the code that creates the ppc64 c-extension suffixes

---

extra_tests/cffi_tests/cffi0/test_parsing.py
lib_pypy/cffi/cparser.py
rpython/tool/cparser/cparser.py

Port python-cffi/cffi#46:
- add a warning when passing `#pragmas` to the `cdef()`
- test and fix for a case where `pycparser` is left in a bogus state
Motivated by https://github.com/python-cffi/cffi/issues/45 .

port cffi PR 46

---

extra_tests/test_sqlite3.py

This commit fixes the failing `test_connection_del` test case in `test_sqlite3.py`.
The test case relies on `gc.collect()` to invoke the `Connection.__del__` method.  But, the `con` list in the `open_many` function is still reachable after the first `open_many(False)` invocation.  (Note: It seems that the exception holds a backtrace, the backtrace holds the frame object, the frame object keeps the `con` list and the `Connection` objects reachable.)
This commit fixes the problem by wrapping the first invocation in a function so that the propagating exception object can be freed before we call `gc.collect()`.

extra_tests: Fix test_sqlite3 test_connection_del

---

extra_tests/cffi_tests/cffi1/test_zdist.py
pypy/module/_cffi_backend/test/_backend_test_c.py
pypy/module/_cffi_backend/test/test_file.py
rpython/jit/backend/zarch/test/conftest.py

PR #4891 merged latest cffi changes to pypy main. There were some failures on main. This PR
- fixes the test_zdist failures
- updates the URL for `test_c.py` to the github-based cffi repo
- starts to re-sync the test_c.py to `_backend_test_c.py`. More work is needed for `test_callback_exception`.
Edit: The PR also contains a fix for a rpython test collection mess up

Fixes for latest cffi testing

---

pypy/module/_cffi_backend/test/_backend_test_c.py
pypy/module/_cffi_backend/test/test_c.py

It is too hard to match the python3/pytest6.2 semantics of the `_assert_unraisable` helper function, so skip the test.

resync test_c.py, skip test_callback_exception

---

pypy/goal/targetpypystandalone.py
rpython/translator/c/src/mem.h

Note that cpyext must be disabled for now, until we fix the issue.

make pypy translate with boehm again

---

extra_tests/test_exceptiongroups.py
lib_pypy/_pypy_exceptiongroups.py

Only implemented the `BaseExceptionGroup` and `ExceptionGroup` classes. No integration rn. 
Based on this implementation: [ExceptionGroup backport](https://github.com/agronholm/exceptiongroup/)
Also, there are still one FIXME and two TODOs:

Partially Implemented ExceptionGroups (from PEP654)

---

extra_tests/test_venv.py
lib-python/3/multiprocessing/popen_spawn_win32.py
lib-python/3/venv/__init__.py

Fixes #4876 
On CPython, there is a work-around for launching a process inside a virtual environment since CPython uses a launcher and not the python exe directly. PyPy does not use a launcher, so disable the work-around
Also fix a long standing problem in post-build testing, when creating a virtual environment on windows.

WIN: Disable WINENV work-around since PyPy does not have a launcher, fix venv creation from a source build

---

pypy/module/array/interp_array.py
pypy/module/array/moduledef.py

Copy `array.typecodes` from CPython, but assert that they match the set of typecodes used in PyPy code.
Hopefully targeting the correct branch this time :)
Addresses part of https://github.com/pypy/pypy/issues/4962.

Add array.typecodes, take 2

---

pypy/module/cmath/interp_cmath.py
pypy/module/cmath/moduledef.py
pypy/module/cmath/test/test_cmath.py

Use `math.pi * 2.0` to define it, as `math.tau` isn't available on Python 2.
@mattip said:
> should also inject the constant into the `math` module
But I don't know what that means, or how to do it. Any clues?
Addresses part of https://github.com/pypy/pypy/issues/4962.

Add cmath.tau, take 2

---

pypy/doc/conf.py

As recommended in the upcoming changes [for readthedocs](https://about.readthedocs.com/blog/2024/07/addons-by-default/)

set html_context and html_baseurl as recommended by readthedocs

---

pypy/module/cpyext/memoryobject.py
pypy/module/cpyext/test/test_memoryobject.py

Fix issue #4992: the behavior of PyMemoryView_FromMemory is backwards.
**I haven't tested this**, but it seems right.
I'm also not sure of the procedure for making changes here.  I'm targetting this pull request at `py3.9` branch, but note that:
- The bug is also present in `py3.10` branch (as well as older versions.)
- This is an API break, so I don't know whether it's okay to change this in a stable release.

Fix readonly flag in PyMemoryView_FromMemory

---

rpython/doc/riscv.rst

This commit refines RISC-V cross-compilation doc:
1. Replace Debian with Ubuntu -- I used Debian in my early draft, but switched to Ubuntu recently because `debootstrap` doesn't work now.
2. Refine the "note" for CPython 2.7.

riscv: Refine RISC-V cross-compilation doc

---

extra_tests/cffi_tests/cffi1/test_zdist.py
extra_tests/cffi_tests/test_c.py
lib_pypy/cffi.dist-info/METADATA
lib_pypy/cffi/__init__.py
lib_pypy/cffi/_embedding.h
lib_pypy/cffi/recompiler.py
pypy/module/_cffi_backend/__init__.py
pypy/module/_cffi_backend/test/_backend_test_c.py
pypy/module/_cffi_backend/test/test_file.py
pypy/tool/import_cffi.patch
pypy/tool/import_cffi.py

- Run `PYTHONPATH=. python2 pypy/tools/release/import_cffi.py` to update extra_tests and lib_pypy
- Fix up lib_pypy/cffi.dist-info/METADATA
- Update pypy/module/_cffi_backend/test/_backend_test_c.py
The test_file test will still fail, since the cffi `main` branch did not update the version, see python-cffi/cffi#116
The METADATA will need re-doing when this is merged to py3.9/py3.10.

update to cffi1.17.0

---

pypy/module/time/test/test_time.py

tzdata provides Kiev as an alternative to Kyiv, but Debian moved it to the tzdata-legacy package, breaking these tests.
cPython also uses this timezone in test_email, and this was fixed in 3.11. I've left that patch out of here, it will get picked up when PyPy switches to 3.11 stdlib.
https://github.com/python/cpython/pull/109251

Use Kyiv instead of Kiev

---

pypy/module/_socket/interp_socket.py

the hardware address for an AF_PACKET socket is 8 bytes, not a string.
This is how it is in CPython, where a PyArg_ParseTuple with data type y* is used.

Fix socket.socket.sendto for AF_PACKET protocol

---

lib_pypy/_pypy_interact.py

use simple interactive console if stdin is closed (issue 2981)

---

pypy/module/cpyext/api.py
pypy/module/thread/test/test_lock.py
rpython/rlib/rthread.py
rpython/rlib/test/test_rthread.py
rpython/translator/c/src/thread.c
rpython/translator/c/src/thread.h
rpython/translator/c/src/thread_win7.c
rpython/translator/c/src/thread_win7.h
rpython/translator/platform/windows.py

This is the first step in updating windows threading code. It replaces the thread locking mutex with a [`SRWLOCK`](https://learn.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks), which is faster. Locally, building pypy2.7 with this branch and then translating PyPy with it made translation go from 1700 seconds (with pypy2.7-v7.3.14) to 1500 seconds (this branch).

Faster win mutex

---

rpython/translator/c/src/thread_win7.c
rpython/translator/c/src/thread_win7.h
rpython/translator/c/src/threadlocal.h

Now that the threading primitives match more closely, use these in a similar way to the pthreads code. Maybe solves #5033 (after merging to py3.10)

refactor windows gil mutex handling to mimic pthreads

---

pypy/interpreter/pyparser/pyparse.py
pypy/interpreter/pyparser/pytokenizer.py
pypy/interpreter/pyparser/test/test_pyparse.py

Fixes #5076, in the spirit of the fix for #4002. I also noticed something else. The SyntaxError in `eval()` does not show the fine-grained error locations where CPython does. Is that easy to fix?
CPython 3.10
```
>>> eval("a =")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<string>", line 1
a =
^
SyntaxError: invalid syntax
>>> eval("a ='\\")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<string>", line 1
a ='\
^
SyntaxError: unterminated string literal (detected at line 1)
```
PyPy 3.10 (with this PR, using pyinteractive)
```
>>>> eval("a =")
Traceback (application-level):
File "<inline>", line 1 in <module>
eval("a =")
SyntaxError: invalid syntax (<string>, line 1)
>>>> eval("a ='\\")
Traceback (application-level):
File …
```

allow unterminated string error to propogate

---

pypy/module/_vmprof/interp_vmprof.py
pypy/module/_vmprof/moduledef.py
pypy/module/_vmprof/test/test__vmprof.py
pypy/module/_vmprof/test/test_direct.py
rpython/rlib/rvmprof/__init__.py
rpython/rlib/rvmprof/cintf.py
rpython/rlib/rvmprof/dummy.py
rpython/rlib/rvmprof/rvmprof.py
rpython/rlib/rvmprof/src/rvmprof.h
rpython/rlib/rvmprof/test/test_rvmprof.py

use vmp_resolve_addr function to get name, file and line number of native functions after profiling with vmprof on pypy.

VMProf: Resolve names of native functions

---

pypy/objspace/std/objectobject.py
pypy/objspace/std/tupleobject.py

This PR is related to #3678.
First I tried add doctrings to tuple. Those doctriings I added are copied from Python 2.7.  
Should I add those from Python 3 instead of Python 2?

Add docstrings to tupleobject

---

pypy/module/cpyext/api.py
pypy/module/cpyext/include/pythread.h
pypy/module/cpyext/src/pythread.c
pypy/module/cpyext/test/test_thread.py

It looks to map fairly directly onto RPyThreadAcquireLockTimed anyway so no new functionality is needed.

Add PyThread_acquire_lock_timed

---

rpython/translator/c/src/entrypoint.c
rpython/translator/c/src/entrypoint.h
rpython/translator/platform/test/test_makefile.py
rpython/translator/platform/test/test_windows.py
rpython/translator/platform/windows.py

This solves #5138 by accepting `wchar_t` for `argv` in `main` and cnverting each argument to utf8 using `WideCharToMultiByte`. found in `kernel32.lib`. For the `WinMain` console-less pypy-w.exe implementation, I additionally used `CommandLineToArgvW(GetCommandLineW(), &argCount)`, which requires linking with `Shell32.lib`. There might be a better way to add the link libraries, but this one works.

on windows, use wchar_t for main(..., argv) in C

---

pypy/module/cpyext/parse/cpyext_object.h

This fails to compile on C++ because it's more strict than C about matching exact function types..

Fix the type of sendfunc

---

pypy/tool/release/make_portable.py
rpython/rlib/rvmprof/cintf.py
rpython/rlib/rvmprof/rvmprof.py
rpython/rlib/rvmprof/src/rvmprof.h
rpython/rlib/rvmprof/src/shared/symboltable.c
rpython/rlib/rvmprof/src/shared/symboltable.h

This will allow VMProf to find native function names via libunwind's function `unw_get_proc_name_by_ip`, which usually finds names, that `dladdr` and `libbacktrace` won't find.
The changes in `make_portable.py` will add `libunwind.so` to the list of dependencies, so that it will be shipped with the PyPy shared object and can be loaded at runtime in `symboltable.c`.
As described by @cfbolz in #5177, a buildbot would need to build a recent version of libunwind for this to work.

VMProf: find native symbol names via libunwind & ship libunwind 

---

rpython/rlib/clibffi.py

Since libffi is such an integral part of PyPy, search for a libffi.a static library and link to it instead of dynamically linking to it. I think this is preferable?
This fixes an edge case when testing a freshly built pypy in the docker images used on linux, libffi is in `/usr/local/lib`, that directory is not in the ldconfig cache, and `subprocess.Popen` is called with `env={}`.

Statically link in libffi if possible

---

extra_tests/test_pypy_remote_debug.py
lib_pypy/_pypy_remote_debug.py
pypy/module/_vmprof/app_vmprof.py
pypy/module/_vmprof/interp_vmprof.py
pypy/module/_vmprof/moduledef.py
pypy/module/_vmprof/test/test__vmprof.py

#5186: instead of using libunwind to symbolify (which crashes), parse the elf files ourselves (which we do for the remote debugger already anyway). This probably has some not implemented corner cases, but at least it can't segfault.

Vmprof manual symbolify

---

pypy/tool/release/make_portable.py
rpython/rlib/rvmprof/__init__.py
rpython/rlib/rvmprof/cintf.py
rpython/rlib/rvmprof/dummy.py
rpython/rlib/rvmprof/rvmprof.py
rpython/rlib/rvmprof/src/rvmprof.h
rpython/rlib/rvmprof/test/test_rvmprof.py

Revert rvmprof changes in #5180 to create a rvmprof `resolve_address` function that uses `libunwind`. Related to #5186

revert rvmprof resolve_address via libunwind

---

pypy/module/imp/interp_imp.py

Remove the extension suffix hack for ppc64le to fix using `.pypy39*` suffix for PyPy3.10.  The hack was added
in 8f1f2a55409636a95379da89e29ded62488d1b2b to preserve backwards compatibility with old extension builds.  However, these extensions were never compatible with PyPy3.10, so it should be safe to remove it now.
Fixes #5196

remove extension suffix hack for ppc64le

---

lib-python/3/test/test_ast.py
pypy/interpreter/pyopcode.py
pypy/module/__builtin__/test/apptest_compile.py

Raise `SyntaxError` rather than `ValueError` on null bytes in source code, to match the behavior of Python 3.11.4+.
Fixes #5234

py3.11: raise `SyntaxError` on null bytes, to match CPython 3.11

---

lib-python/3/dis.py

Disable the special branch for `LOAD_GLOBAL` disassembly introduced in CPython 3.11.  The bytecode in PyPy has not been changed, and it causes incorrect disassembly.
Fixes #5238

Fix `LOAD_GLOBAL` disassembly on PyPy3.11

---

lib-python/3/datetime.py

Fix pure Python implementation of `fromisoformat()` to reject spaces in fractional part of time specifications.  This matches the behavior of the C implementation in CPython, and prevents the method from parsing them incorrectly.
This fixes Django's test suite by enabling a fallback to their own (working) parser.
Backports: https://github.com/python/cpython/pull/130962

Fix `datetime.*.fromisoformat()` to reject spaces in fraction part

---

rpython/translator/c/src/precommondefs.h

This applies to the 3.10 and 3.11 branches.
Fixes: #5229

Get 32-bit ARM translating on old platforms again

---

lib_pypy/_cffi_ssl/_stdssl/__init__.py
lib_pypy/_cffi_ssl/_stdssl/error.py

Remove some duplicate code that I've discovered in `_cffi_ssl` module while debugging https://github.com/python-trio/trio/issues/3253.

Remove some duplicate code from `_cffi_ssl` module

---

lib_pypy/_cffi_ssl/_stdssl/error.py

Add missing handlers for `LIB_ERR_SYS` in `pyssl_error()`.  This was added to CPython in python/cpython@f4b31edf2d9d72878dab1f66a36913b5bcc848ec, and seems to be required for OpenSSL 3.4+.
Adding this handler fixes flaky test failures reported in python-trio/trio#3253.

[_cffi_ssl] Add missing LIB_ERR_SYS handling

---

rpython/translator/platform/windows.py

While working on a more modern LLVM translation backend for PyPy I happened to catch this argument processing block of code in the Windows launcher. I think it can be made simpler by just using wWinMain and passing \_\_wargv to pypy\_main\_startup rather than having to do the command line parsing logic ourselves with CommandLineToArgvW.

Use wWinMain to remove the need for command line argument processing

---

pypy/module/time/interp_time.py

nanosleep() is documented as returning -1 on error and setting errno.

Fix EINTR handling in time.sleep() on Mac

---

pypy/pytest-A.py

The existing split was unnecessary and resulted in nonsensical calls to `pytest -A .../apptest_foo.py` which mess up test results, e.g. [here](https://buildbot.pypy.org/summary/longrepr?testname=&builder=pypy-c-jit-macos-arm64&build=1059&mod=pypy.interpreter.astcompiler.test.apptest_exceptiongroup)
IIRC, I tried to make that do the right thing (i.e skip instead of erroring) back in the day but didn't find a reasonable way. Calling `pytest -A` on the parent test directory does the right thing though.

Fix test collection for pytest-A on macos-arm64

---

rpython/rtyper/lltypesystem/rordereddict.py
rpython/rtyper/test/test_rdict.py
rpython/rtyper/test/test_rordereddict.py

#5257 fix a subtle invariant violation of PyPy's ordered dictionaries in the `move_to_first` logic

Ordereddict move to first bug

---

lib_pypy/cffi-1.18.0.dev0.dist-info/METADATA

Remove the incorrect `pycparser` dependency from `cffi` dist-info. PyPy is vendoring `pycparser` inside `cffi`, and not as a global package.  Having an explicit dependency meant that `pip check` would fail in environments without `pycparser` manually installed, in particular in a fresh venv.
Fixes #5306

Remove `pycparser` dep from `cffi` dist-info
